#! /usr/bin/env ruby

in_cmd = ARGV[0]
out_cmd = ARGV[1]

in_io = IO.popen(in_cmd)
out_io = IO.popen(out_cmd, "w+")

printer = Thread.new do
  out_io.each { |l| puts l }
end

in_io.each_line do |line|
  puts "'#{line.chomp}' Done?"
  out_io.write line
  STDIN.gets
end
